{% set name = "root" %}
{% set version = "6.16.00" %}
{% set hash = "c8415df5a0ec1619df5da0a2a36d79a47f1cf5927ee66cb5f045b39bb250c79a" %}
{% set variant = "openblas" %}
{% set clang_version = "5.0.0" %}
{% set clang_patches_version = "6.16.00" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/root-project/root/archive/v{{ version|replace(".","-") }}.tar.gz
  sha256: {{ hash }}
  folder: root-source
  patches:
    - patches/root-x.xx.xx_cling-runtime-sysroot.patch
    - patches/root-6.18.00_root_config_cxxstd_flags.patch
    - patches/root-6.16.02_allow_setting_clang_version.patch  # [osx]
    - patches/root-6.16.02_not_test_cxx11_clang_4.patch  # [osx]
    - patches/root-x.xx.xx_python_mac_os.patch  # [osx]
    - patches/root-x.xx.xx-copy-abspath-headers.patch  # [osx]
    - patches/root-x.xx.xx-osx-remove-hardcoded-sysroot.patch  # [osx]

build:
  number: 4
  skip: True  # [win]
  features:
    - blas_{{ variant }}
  run_exports:
    # https://abi-laboratory.pro/?view=timeline&l=root
    - {{ pin_subpackage('root', max_pin='x.x.x') }}
  ignore_prefix_files:
    # FIXME: Figure out how to correct the paths in the PCH
    - etc/allDict.cxx.pch  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - cmake
    - git
    - pkg-config
  host:
    - {{ compiler('c') }}  # [linux]
    - {{ compiler('cxx') }}  # [linux]
    - {{ compiler('fortran') }}  # [linux]
    - afterimage
    - openblas
    - cfitsio
    - clangdev={{ clang_version }}
    - clang_variant * cling_{{ clang_patches_version }}
    - davix
    - fftw
    - freetype
    - giflib
    - gsl
    - gdk-pixbuf
    - krb5  # [osx]
    - libglu  # [linux]
    - libpng
    - librsvg
    - libtiff
    - libxml2
    - llvmdev==5
    - lz4
    - lz4-c
    # - mysql
    - numpy
    - openssl
    - pcre
    # - postgresql
    - pythia8
    - python
    - qt
    - sqlite
    - tbb
    - tbb-devel
    - vdt
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xrootd
    - xz
    - zlib
  run:
    - compilers
    - {{ pin_compatible('numpy') }}
    - afterimage
    - openblas
    - cfitsio
    # - clangdev={{ clang_version }}
    # - clang_variant * cling_{{ version }}
    - davix
    - fftw
    - freetype
    - giflib
    - gsl
    - gdk-pixbuf
    - krb5  # [osx]
    - libglu  # [linux]
    - libpng
    - librsvg
    - libtiff
    - libxml2
    - lz4
    - lz4-c
    # - mysql
    - metakernel
    - notebook
    - openssl
    - pcre
    # - postgresql
    - pythia8
    - python
    - qt
    - sqlite
    - tbb
    - tbb-devel
    - vdt
    - xorg-libx11  # [linux]
    - xorg-libxau  # [linux]
    - xorg-libxcursor  # [linux]
    - xorg-libxext  # [linux]
    - xorg-libxft  # [linux]
    - xorg-libxpm  # [linux]
    - xrootd
    - xz
    - zlib
  run_constrained:
    # Items listed here conflict with ROOT
    # FIXME Add support in ROOT for building with an external cling
    - cling 9999
    - root5 9999

test:
  requires:
    - ipython
  imports:
    - ROOT
    - JupyROOT
  commands:
    - ipython -c 'import JsMVA'
    - root -l -b -q -x
    - root -l -b -q -x ${RECIPE_DIR}/test.cpp
    - root -l -b -q -x ${RECIPE_DIR}/test.cpp++
    # When testing with -e, explicitly set the return code to zero
    - root -b -l -q -x -e '2+3; 0'
    - root -b -l -q -x -e 'gSystem->LoadAllLibraries(); 0'
    - echo ${CONDA_BUILD_SYSROOT}  # [osx]
    # There should be no hard coded references to the SDK
    - "! grep -r ${CONDA_BUILD_SYSROOT} ${CONDA_PREFIX}/lib"  # [osx]
    # Check the thisroot scripts work
    - thisroot.sh
    - thisroot.csh
    - thisroot.fish

about:
  home: https://root.cern/
  license: LGPL-2.1
  license_family: LGPL
  license_file: root-source/LICENSE
  summary: 'Data Analysis Framework'
  doc_url: https://root.cern/documentation
  dev_url: https://github.com/root-project/root/

extra:
  recipe-maintainers:
    - chrisburr
    - henryiii
    - bluehood
    - egpbos
