travis:
  secure:
    BINSTAR_TOKEN: Rs9n7X2iw2E16Zfba8HN78v7Y2uQApNVKsvUmJqfoxNkmtGVdG3rDGX0o7ViJDnJqPurUTa3GBFNZu0vLN432rgj7Sr46ytAKdLjxKGGydrspO3L1L3VKiIQi7FiC/UFj/vulQLOW6bsHDpPoQ5qFoCItQBgpfenaJN+TJpQWs70hr/tgGyOZsCo1gX3xPqtQeJ6V3rURUpFPiPbunrnPt4nzsp3RwnM4l/AgPNp4HIpnjw2qksuTdX6m0e/0bE+TYo1Fm8rVTcVrlJrRt46wzXMXxaosXfg7efEjii6Y8JdtP7YIcLRIz3dJtZvBjZZIBqBy6UudC/cahZp9LYw5Q3pOKN/VAvSBVyyigD9ow8IUsLLZUozGEUxRYrCBQcoSoEVCOPvzDd4K/gtScOvFdh9wVWwvxiq6eCjXa715XyQy/WA6d9SrZtcrUrg5TM+YRoC0Tj2bm3r4RdTORgHv/nKWNkWgwYqG8xKffCU2UbD5SuKMXo0nV4KLNwedMbhjecmR0EbXTGrg0jmcBugd680LeQ4hu9AjwuaKjF9WrOOTo3zjl98MdCOa6eCTOxxTdsTKo02C52r/IDwzO38HywrI5b+3mjOlDza8V4OBhVeOou+Wfis8nBXvBT0gOJcZ6qzkpjP70Qe8kcwmUraXU9OYc+rpuLc3bbDv3hT75g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
